SELECT VENDA_TAMANHO.TAMANHO,
    VENDA_TAMANHO.ANO,
    VENDA_TAMANHO.QUANTIDADE,
    ROUND(
        (VENDA_TAMANHO.QUANTIDADE / VENDA_TOTAL.QUANTIDADE) * 100,
        2
    ) AS PARTICIPACAO
FROM (
        SELECT TP.TAMANHO,
            YEAR(NF.DATA_VENDA) AS ANO,
            SUM(INF.QUANTIDADE) AS QUANTIDADE
        FROM TABELA_DE_PRODUTOS TP
            INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
            INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
        WHERE YEAR(NF.DATA_VENDA) = 2016
        GROUP BY TP.TAMANHO,
            YEAR(NF.DATA_VENDA)
    ) AS VENDA_TAMANHO
    INNER JOIN (
        SELECT YEAR(NF.DATA_VENDA) AS ANO,
            SUM(INF.QUANTIDADE) AS QUANTIDADE
        FROM TABELA_DE_PRODUTOS TP
            INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
            INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
        WHERE YEAR(NF.DATA_VENDA) = 2016
        GROUP BY YEAR(NF.DATA_VENDA)
    ) AS VENDA_TOTAL ON VENDA_TAMANHO.ANO = VENDA_TOTAL.ANO
ORDER BY VENDA_TAMANHO.QUANTIDADE DESC