use sucos_vendas;
SELECT EMBALAGEM,
    AVG(PRECO_DE_LISTA) AS PRECO_MEDIO,
    CASE
        WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
        WHEN PRECO_DE_LISTA >= 7
        AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
        ELSE 'PRODUTO BARATO'
    END AS STATUS_PRECO
FROM tabela_de_produtos
GROUP BY EMBALAGEM